routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ReportController;

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('officials', 'OfficialController');

    Route::get('individuals/normal', 'IndividualController@normal')->name('individuals.normal');
    Route::get('individuals/critical', 'IndividualController@critical')->name('individuals.critical');
    Route::resource('individuals', 'IndividualController');

    Route::resource('doctors', 'DoctorController');

    Route::resource('histories', 'HistoryController');

    Route::resource('symptoms', 'SymptomController');

    Route::get('/device_location', 'HomeController@deviceLocation')->name('deviceLocation');
});


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Route::resource('news', 'NewsController');

Route::resource('emergencyNumbers', 'EmergencyNumberController');


Route::resource('locations', 'LocationController');

Route::resource('announcements', 'AnnouncementController');

Route::resource('safeties', 'SafetyController');


// Official
Route::group(['prefix' => 'official', 'as' => 'official.'], function () {
    Route::get('/login', 'AuthOfficial\OfficialLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AuthOfficial\OfficialLoginController@login')->name('login');
    Route::post('/logout', 'AuthOfficial\OfficialLoginController@logout')->name('logout');
});
Route::resource('nepalTrends', 'NepalTrendController');
Route::get('patient-report', 'ReportController@patientReport')->name('patientReport');
Route::get('profile', 'UserController@profile')->name('profile');
Route::get('users', 'UserController@index')->name('users.index');


Route::resource('meetings', 'MeetingController');

Route::resource('serverNumbers', 'ServerNumberController');

Route::resource('dangerZones', 'DangerZoneController');

resources/views/device_location.blade.php
@extends('layouts.app')
@section('css')
<link href='https://api.mapbox.com/mapbox.js/v3.2.1/mapbox.css' rel='stylesheet' />
<style>
    body {
        margin: 0;
        padding: 0;
    }

    /* #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
    } */

    .info {
        position: absolute;
        top: 10px;
        right: 10px;
    }

    .info div {
        background: #fff;
        padding: 10px;
        border-radius: 3px;
    }
</style>
@endsection

@section('content')
<div id='map' class="map" style="height: 750px"></div>
<div id='info' style="margin-top:40px" class='info'></div>
@endsection
@section('scripts')
<script src='https://api.mapbox.com/mapbox.js/v3.2.1/mapbox.js'></script>
<script>
    let individuals = {!! $individuals !!}
    L.mapbox.accessToken = 'pk.eyJ1Ijoic2FuYW1zaHJlc3RoYTEyMyIsImEiOiJjanpqcDhwaG0wNjNxM291aXZybjd3eng2In0.KOeiGVngAUlaFdVxsKFaNg';

    var info = document.getElementById('info');

    let setViewCoordinate = [27.7172, 85.3240];
    url = new URL(window.location.href);
    if (url.searchParams.get('lat')) {
        setViewCoordinate[0] = url.searchParams.get('lat');
    }
    if (url.searchParams.get('lng')) {
        setViewCoordinate[1] = url.searchParams.get('lng');
    }

    var map = L.mapbox.map('map')
        .setView(setViewCoordinate, 13)
        .addLayer(L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v11'));
    var myLayer = L.mapbox.featureLayer().addTo(map);

    let geoJson = {
        type: 'Feature',
        features: []
    };

console.log(individuals)
    individuals.forEach((val) => {
        if (val.name) {
            console.log(val.status)
            if (val.status == 1) {
                markerColor = '#3dff03';
            } else if (val.status == 2) {
                markerColor = '#39bd11';
            } else if (val.status == 3) {
                markerColor = '#ffdf0d';;
            } else if (val.status == 4) {
                markerColor = '#ffa20d';
            } else if (val.status == 5) {
                markerColor = '#ff0d0d';
            } else {
                markerColor = '#000000';
            }
            var feature = {
                "type": "Feature",
                "properties": {
                    "id": val.id,
                    "name": val.name,
                    "phone": val.phone,
                    "iconSize": [15, 15],
                    "address": val.address,
                    icon: {
                        className: '', // class name to style
                        html: '<div style="height: 25px;width: 25px;border-radius: 50% !important; background-color: ' + markerColor + '">' +
                            '<p style="padding-left:8px;">' + val.status + '</p></div>',
                        iconSize: null // size of icon, use null to set the size in CSS
                    }
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [val.longitude, val.latitude]
                }
            }
            geoJson.features.push(feature)
        }

    });
    myLayer.on('layeradd', function(e) {
        var marker = e.layer,
            feature = marker.feature;
        marker.setIcon(L.divIcon(feature.properties.icon));
    });
    myLayer.setGeoJSON(geoJson);

    // Listen for individual marker hover.
    myLayer.on('mousemove', function(e) {
        // Force the popup closed.
        e.layer.closePopup();
        var feature = e.layer.feature;
        var content = '<div><strong>Individual Name: ' + feature.properties.name + '</strong><br>' +
            '<label>Contact Number: ' + feature.properties.phone + '</label><br>' +
            '<label>Address: ' + feature.properties.address + '</label></div>';

        info.innerHTML = content;
    });
    // Listen for individual marker click.
    myLayer.on('click', function(e) {
        // Force the popup closed.
        var feature = e.layer.feature;
        let now = '{!! \Carbon\Carbon::now() !!}';
        window.location.href = "/corona/individuals/" + feature.properties.id;
    });
    // Clear the tooltip when map is clicked.
    map.on('move', empty);
    // Trigger empty contents when the script
    // has loaded on the page.
    empty();

    function empty() {
        info.innerHTML = '<div><strong>Click a marker</strong></div>';
    }
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if($nepalTrend != null)
    <div class="row" style="padding:2px">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table" id="nepalTrends-table">
                    <thead  style="background:#337ab7">
                        <tr>
                            <th>Tested Positive</th>
                    <th>Tested Negative</th>
                    <th>Tested Total</th>
                    <th>In Isolation</th>
                    <th>Recovered</th>
                    <th>Deaths</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ $nepalTrend->tested_positive }}</td>
                        <td>{{ $nepalTrend->tested_negative }}</td>
                        <td>{{ $nepalTrend->tested_total }}</td>
                        <td>{{ $nepalTrend->in_isolation }}</td>
                        <td>{{ $nepalTrend->recovered }}</td>
                        <td>{{ $nepalTrend->deaths }}</td>
                        <td>{{ $nepalTrend->created_at }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @endif
    <div class="row">
        <a href="{{route('individuals.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Patients</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/birami.png')}}" alt=""></div>
            </a>
        <a href="{{route('doctors.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Doctor</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/doctor.png')}}" alt=""></div>
        </a>
        <a href="{{route('deviceLocation')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Map</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/map.png')}}" alt=""></div>
        </a>
        <a href="{{route('emergencyNumbers.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Emergency Number</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/number.png')}}" alt=""></div>
        </a>
        <a href="{{route('news.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">News</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/news.png')}}" alt=""></div>
        </a>
        <a href="{{route('announcements.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">Announcements</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/announcements.png')}}" alt=""></div>
        </a>
        <a href="{{route('safeties.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">Safeties</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/safety_tips.png')}}" alt=""></div>
        </a>

    </div>
</div>
@endsection