routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ReportController;

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('officials', 'OfficialController');

    Route::get('individuals/normal', 'IndividualController@normal')->name('individuals.normal');
    Route::get('individuals/critical', 'IndividualController@critical')->name('individuals.critical');
    Route::resource('individuals', 'IndividualController');

    Route::resource('doctors', 'DoctorController');

    Route::resource('histories', 'HistoryController');

    Route::resource('symptoms', 'SymptomController');

    Route::get('/device_location', 'HomeController@deviceLocation')->name('deviceLocation');
});


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Route::resource('news', 'NewsController');

Route::resource('emergencyNumbers', 'EmergencyNumberController');


Route::resource('locations', 'LocationController');

Route::resource('announcements', 'AnnouncementController');

Route::resource('safeties', 'SafetyController');


// Official
Route::group(['prefix' => 'official', 'as' => 'official.'], function () {
    Route::get('/login', 'AuthOfficial\OfficialLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AuthOfficial\OfficialLoginController@login')->name('login');
    Route::post('/logout', 'AuthOfficial\OfficialLoginController@logout')->name('logout');
});
Route::resource('nepalTrends', 'NepalTrendController');
Route::get('patient-report', 'ReportController@patientReport')->name('patientReport');
Route::get('profile', 'UserController@profile')->name('profile');
Route::get('users', 'UserController@index')->name('users.index');


Route::resource('meetings', 'MeetingController');

Route::resource('serverNumbers', 'ServerNumberController');

Route::resource('dangerZones', 'DangerZoneController');

app/Http/Controllers/AuthOfficial/OfficialLoginController.php
<?php

namespace App\Http\Controllers\AuthOfficial;

use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;

class OfficialLoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/official';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    public function showLoginForm()
    {
        return view('auth_official.login');
    }

    protected function guard()
    {
        return Auth::guard('official');
    }
}

resources/views/auth_official/home.blade.php
@extends('auth_official.layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <a href="{{route('official.individuals.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Patients</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/birami.png')}}" alt=""></div>
            </a>
        <a href="{{route('official.doctors.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Doctor</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/doctor.png')}}" alt=""></div>
        </a>
        {{-- <a href="{{route('official.deviceLocation')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Map</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/map.png')}}" alt=""></div>
        </a> --}}
        <a href="{{route('official.emergencyNumbers.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
                <div class="text-center"> <b style="font-size:24px;color:white">Emergency Number</b> </div>
            <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/number.png')}}" alt=""></div>
        </a>
        
        <a href="{{route('official.announcements.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">Announcements</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/announcements.png')}}" alt=""></div>
        </a>
        <a href="{{route('official.safeties.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">Safeties</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/safety_tips.png')}}" alt=""></div>
        </a>
        <a href="{{route('official.news.index')}}" class="col-md-3" style="background:#51515c; border:5px solid white">
            <div class="text-center"> <b style="font-size:24px;color:white">News</b> </div>
        <div><img style="padding:50px" class="img-responsive" src="{{asset('images/icons/news.png')}}" alt=""></div>
        </a>

    </div>
</div>
@endsection

resources/views/auth_official/login.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{config('app.name')}}| Official Login</title>

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="shortcut icon" type="image/png" href="{{asset('/images/favicon/favicon.png')}}" />
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="{{ url('/home') }}"><b>{{config('app.name')}} </b></a>
        </div>

        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">Sign in as Official</p>

            <form method="post" action="{{ url('/official/login') }}">
                {!! csrf_field() !!}

                <div class="form-group has-feedback {{ $errors->has('email') ? ' has-error' : '' }}">
                    <input type="email" class="form-control" name="email" value="{{ old('email') }}"
                        placeholder="Email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    @if ($errors->has('email'))
                    <span class="help-block">
                        <strong>{{ $errors->first('email') }}</strong>
                    </span>
                    @endif
                </div>

                <div class="form-group has-feedback{{ $errors->has('password') ? ' has-error' : '' }}">
                    <input type="password" class="form-control" placeholder="Password" name="password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    @if ($errors->has('password'))
                    <span class="help-block">
                        <strong>{{ $errors->first('password') }}</strong>
                    </span>
                    @endif

                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox" name="remember"> Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            {{-- <a href="{{ url('/password/reset') }}">I forgot my password</a><br> --}}
            {{-- <a href="{{ url('/register') }}" class="text-center">Register a new membership</a> --}}

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
    </script>
</body>

</html>