routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ReportController;

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('officials', 'OfficialController');

    Route::get('individuals/normal', 'IndividualController@normal')->name('individuals.normal');
    Route::get('individuals/critical', 'IndividualController@critical')->name('individuals.critical');
    Route::resource('individuals', 'IndividualController');

    Route::resource('doctors', 'DoctorController');

    Route::resource('histories', 'HistoryController');

    Route::resource('symptoms', 'SymptomController');

    Route::get('/device_location', 'HomeController@deviceLocation')->name('deviceLocation');
});


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Route::resource('news', 'NewsController');

Route::resource('emergencyNumbers', 'EmergencyNumberController');


Route::resource('locations', 'LocationController');

Route::resource('announcements', 'AnnouncementController');

Route::resource('safeties', 'SafetyController');


// Official
Route::group(['prefix' => 'official', 'as' => 'official.'], function () {
    Route::get('/login', 'AuthOfficial\OfficialLoginController@showLoginForm')->name('login');
    Route::post('/login', 'AuthOfficial\OfficialLoginController@login')->name('login');
    Route::post('/logout', 'AuthOfficial\OfficialLoginController@logout')->name('logout');
});
Route::resource('nepalTrends', 'NepalTrendController');
Route::get('patient-report', 'ReportController@patientReport')->name('patientReport');
Route::get('profile', 'UserController@profile')->name('profile');
Route::get('users', 'UserController@index')->name('users.index');


Route::resource('meetings', 'MeetingController');

Route::resource('serverNumbers', 'ServerNumberController');

Route::resource('dangerZones', 'DangerZoneController');

app/Models/EmergencyNumber.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class EmergencyNumber
 * @package App\Models
 * @version March 29, 2020, 10:54 am +0545
 *
 * @property string title
 * @property string number
 */
class EmergencyNumber extends Model
{

    public $table = 'emergency_numbers';
    



    public $fillable = [
        'title',
        'number'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'number' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/EmergencyNumberController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEmergencyNumberRequest;
use App\Http\Requests\UpdateEmergencyNumberRequest;
use App\Repositories\EmergencyNumberRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\EmergencyNumber;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use Flash;
use Response;

class EmergencyNumberController extends AppBaseController
{
    /** @var  EmergencyNumberRepository */
    private $emergencyNumberRepository;

    public function __construct(EmergencyNumberRepository $emergencyNumberRepo)
    {
        $this->emergencyNumberRepository = $emergencyNumberRepo;
    }

    /**
     * Display a listing of the EmergencyNumber.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $emergencyNumbers = EmergencyNumber::orderBy('id', 'desc')->get();

        return view('emergency_numbers.index')
            ->with('emergencyNumbers', $emergencyNumbers);
    }

    /**
     * Show the form for creating a new EmergencyNumber.
     *
     * @return Response
     */
    public function create()
    {
        return view('emergency_numbers.create');
    }

    /**
     * Store a newly created EmergencyNumber in storage.
     *
     * @param CreateEmergencyNumberRequest $request
     *
     * @return Response
     */
    public function store(CreateEmergencyNumberRequest $request)
    {
        $input = $request->all();

        $emergencyNumber = $this->emergencyNumberRepository->create($input);

        Flash::success('Emergency Number saved successfully.');

        return redirect(route('emergencyNumbers.index'));
    }

    /**
     * Display the specified EmergencyNumber.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $emergencyNumber = $this->emergencyNumberRepository->find($id);

        if (empty($emergencyNumber)) {
            Flash::error('Emergency Number not found');

            return redirect(route('emergencyNumbers.index'));
        }

        return view('emergency_numbers.show')->with('emergencyNumber', $emergencyNumber);
    }

    /**
     * Show the form for editing the specified EmergencyNumber.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $emergencyNumber = $this->emergencyNumberRepository->find($id);

        if (empty($emergencyNumber)) {
            Flash::error('Emergency Number not found');

            return redirect(route('emergencyNumbers.index'));
        }

        return view('emergency_numbers.edit')->with('emergencyNumber', $emergencyNumber);
    }

    /**
     * Update the specified EmergencyNumber in storage.
     *
     * @param int $id
     * @param UpdateEmergencyNumberRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmergencyNumberRequest $request)
    {
        $emergencyNumber = $this->emergencyNumberRepository->find($id);

        if (empty($emergencyNumber)) {
            Flash::error('Emergency Number not found');

            return redirect(route('emergencyNumbers.index'));
        }

        $emergencyNumber = $this->emergencyNumberRepository->update($request->all(), $id);

        Flash::success('Emergency Number updated successfully.');

        return redirect(route('emergencyNumbers.index'));
    }

    /**
     * Remove the specified EmergencyNumber from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $emergencyNumber = $this->emergencyNumberRepository->find($id);

        if (empty($emergencyNumber)) {
            Flash::error('Emergency Number not found');

            return redirect(route('emergencyNumbers.index'));
        }

        $this->emergencyNumberRepository->delete($id);

        Flash::success('Emergency Number deleted successfully.');

        return redirect(route('emergencyNumbers.index'));
    }

    public function checkGuard()
    {
        if (Auth::guard()->check()) {
            $path = "";
            return $path;
        } elseif (Auth::guard('official')->check()) {
            $path = "auth_official.pages.";
            return $path;
        }
    }
}

resources/views/auth_official/pages/emergency_numbers/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Emergency Number
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'emergencyNumbers.store']) !!}

                        @include('emergency_numbers.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/auth_official/pages/emergency_numbers/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Emergency Number
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($emergencyNumber, ['route' => ['emergencyNumbers.update', $emergencyNumber->id], 'method' => 'patch']) !!}

                        @include('emergency_numbers.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/auth_official/pages/emergency_numbers/fields.blade.php
<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<!-- Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('number', 'Number:') !!}
    {!! Form::text('number', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('emergencyNumbers.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/auth_official/pages/emergency_numbers/index.blade.php
@extends('auth_official.layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Emergency Numbers</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('emergencyNumbers.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('emergency_numbers.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $emergencyNumbers])

        </div>
    </div>
@endsection

resources/views/auth_official/pages/emergency_numbers/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Emergency Number
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('emergency_numbers.show_fields')
                    <a href="{{ route('emergencyNumbers.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/auth_official/pages/emergency_numbers/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $emergencyNumber->id }}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{{ $emergencyNumber->title }}</p>
</div>

<!-- Number Field -->
<div class="form-group">
    {!! Form::label('number', 'Number:') !!}
    <p>{{ $emergencyNumber->number }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $emergencyNumber->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $emergencyNumber->updated_at }}</p>
</div>

resources/views/auth_official/pages/emergency_numbers/table.blade.php
<div class="table-responsive">
    <table class="table" id="emergencyNumbers-table">
        <thead>
            <tr>
                <th>Title</th>
        <th>Number</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($emergencyNumbers as $emergencyNumber)
            <tr>
                <td>{{ $emergencyNumber->title }}</td>
            <td>{{ $emergencyNumber->number }}</td>
                <td>
                    {!! Form::open(['route' => ['emergencyNumbers.destroy', $emergencyNumber->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('emergencyNumbers.show', [$emergencyNumber->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{{ route('emergencyNumbers.edit', [$emergencyNumber->id]) }}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>